// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using QuanLyMonHocDoAn.Models;

#nullable disable

namespace QuanLyMonHocDoAn.Migrations
{
    [DbContext(typeof(QldetainckhContext))]
    [Migration("20240410090501_v1")]
    partial class v1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Account", b =>
                {
                    b.Property<int>("MaAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaAccount"));

                    b.Property<string>("Email")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("HoVaTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("MaTypeAccount")
                        .HasColumnType("int");

                    b.Property<string>("Pass")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.Property<string>("UserName")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaAccount")
                        .HasName("PK__ACCOUNT__0A2B8E3443ADF5D7");

                    b.HasIndex("MaTypeAccount");

                    b.ToTable("ACCOUNT", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Bienbanchamdecuong", b =>
                {
                    b.Property<int>("IdbienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBienBan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdbienBan"));

                    b.Property<string>("DanhGia")
                        .HasColumnType("nvarchar(max)");

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<int?>("IdDangKy")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("MinhChung")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("IdbienBan")
                        .HasName("PK__BIENBANC__61A114E2EED07913");

                    b.ToTable("BIENBANCHAMDECUONG", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Bienbannghiemthu", b =>
                {
                    b.Property<int>("IdbienBan")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDBienBan");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdbienBan"));

                    b.Property<double?>("Diem")
                        .HasColumnType("float");

                    b.Property<string>("LinkBienBan")
                        .HasMaxLength(250)
                        .HasColumnType("nvarchar(250)");

                    b.Property<int?>("MaDeTai")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("NhanXet")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("IdbienBan")
                        .HasName("PK__BIENBANN__D0123202EAFC80F7");

                    b.HasIndex("MaDeTai");

                    b.HasIndex("MaHoiDong");

                    b.ToTable("BIENBANNGHIEMTHU", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chitietdonxingiahan", b =>
                {
                    b.Property<int>("MaCtdxgh")
                        .HasColumnType("int")
                        .HasColumnName("MaCTDXGH");

                    b.Property<int?>("IsAccept")
                        .HasColumnType("int");

                    b.Property<string>("LinkDonXin")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("NgayGiaHan")
                        .HasColumnType("date");

                    b.Property<DateOnly?>("NgayHoanThanh")
                        .HasColumnType("date");

                    b.HasKey("MaCtdxgh")
                        .HasName("PK__CHITIETD__79A1495864A38662");

                    b.ToTable("CHITIETDONXINGIAHAN", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chitiethoidongdecuong", b =>
                {
                    b.Property<int>("Idct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idct"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaHoiDong")
                        .HasColumnType("int");

                    b.HasKey("Idct");

                    b.ToTable("CHITIETHOIDONGDECUONG", null, t =>
                        {
                            t.HasTrigger("SuaTV");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chitiethoidongnghiemthu", b =>
                {
                    b.Property<int>("Idct")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDCT");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Idct"));

                    b.Property<int>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int>("MaHoiDong")
                        .HasColumnType("int");

                    b.HasKey("Idct");

                    b.ToTable("CHITIETHOIDONGNGHIEMTHU", null, t =>
                        {
                            t.HasTrigger("SuaTVNT");
                        });

                    b.HasAnnotation("SqlServer:UseSqlOutputClause", false);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chitietnhom", b =>
                {
                    b.Property<int>("IdCtnhom")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IdCTNhom");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IdCtnhom"));

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("IddangKy")
                        .HasColumnType("int")
                        .HasColumnName("IDDangKy");

                    b.Property<string>("MaNhom")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaSoSinhVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("TrangThai")
                        .HasColumnType("int");

                    b.HasKey("IdCtnhom");

                    b.ToTable("CHITIETNHOM", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chuongtrinh", b =>
                {
                    b.Property<string>("MaCt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCT");

                    b.Property<string>("TenCt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("TenCT");

                    b.HasKey("MaCt");

                    b.ToTable("CHUONGTRINH", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Dangky", b =>
                {
                    b.Property<int>("IddangKy")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasColumnName("IDDangKy");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("IddangKy"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool?>("KetQua")
                        .HasColumnType("bit");

                    b.Property<string>("LinkDeCuong")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("MaNhom")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaSoSinhVien")
                        .IsRequired()
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateTime?>("NgayDangKy")
                        .HasColumnType("datetime");

                    b.Property<string>("TenDeTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("TrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasDefaultValue(1);

                    b.HasKey("IddangKy")
                        .HasName("PK__DANGKY__735660836B7DE7F7");

                    b.ToTable("DANGKY", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Detai", b =>
                {
                    b.Property<int>("MaDeTai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaDeTai"));

                    b.Property<string>("GhiChu")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("KetQua")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<decimal?>("KinhPhiDuKien")
                        .HasColumnType("money");

                    b.Property<string>("LinkDeTai")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int");

                    b.Property<int?>("MaHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("MaNganh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaNhom")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("MaSoSinhVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<int?>("MaTrangThai")
                        .HasColumnType("int");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime");

                    b.Property<DateTime?>("NgayThucHien")
                        .HasColumnType("datetime");

                    b.Property<string>("TenDeTai")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("MaDeTai")
                        .HasName("PK__DETAI__9F967D5BB67B2C6A");

                    b.HasIndex("MaGiangVien");

                    b.HasIndex("MaHoiDong");

                    b.HasIndex("MaNganh");

                    b.HasIndex("MaTrangThai");

                    b.ToTable("DETAI", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Donxingiahan", b =>
                {
                    b.Property<int>("MaDonXinGiaHan")
                        .HasColumnType("int");

                    b.Property<int?>("MaCtdxgh")
                        .HasColumnType("int")
                        .HasColumnName("MaCTDXGH");

                    b.Property<int?>("MaDeTai")
                        .HasColumnType("int");

                    b.Property<int?>("MaGiangVien")
                        .HasColumnType("int");

                    b.HasKey("MaDonXinGiaHan")
                        .HasName("PK__DONXINGI__CD4EFD9BDCF17B9F");

                    b.HasIndex("MaCtdxgh");

                    b.HasIndex("MaDeTai");

                    b.HasIndex("MaGiangVien");

                    b.ToTable("DONXINGIAHAN", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Giangvien", b =>
                {
                    b.Property<int>("MaGiangVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaGiangVien"));

                    b.Property<string>("Gmail")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<int?>("MaAccount")
                        .HasColumnType("int");

                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCT");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaSoGiangVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("Nganh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("TenGiangVien")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<string>("TrinhDo")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaGiangVien")
                        .HasName("PK__GIANGVIE__C03BEEBAEF35B90B");

                    b.ToTable("GIANGVIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Hoidongduyetdecuong", b =>
                {
                    b.Property<int>("MaHoiDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoiDong"));

                    b.Property<string>("MaCt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCT");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<bool?>("SoLuongTv")
                        .HasColumnType("bit")
                        .HasColumnName("SoLuongTV");

                    b.Property<string>("TenHoiDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoiDong")
                        .HasName("PK__HOIDONGD__998808B357E61839");

                    b.ToTable("HOIDONGDUYETDECUONG", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Hoidongnghiemthu", b =>
                {
                    b.Property<int>("MaHoiDong")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaHoiDong"));

                    b.Property<string>("MaCt")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)")
                        .HasColumnName("MaCT");

                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime?>("NgayNghiemThu")
                        .HasColumnType("datetime");

                    b.Property<bool?>("SoLuongTv")
                        .HasColumnType("bit")
                        .HasColumnName("SoLuongTV");

                    b.Property<string>("TenHoiDong")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaHoiDong")
                        .HasName("PK__HOIDONGN__998808B3C1A427BD");

                    b.HasIndex("MaKhoa");

                    b.ToTable("HOIDONGNGHIEMTHU", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Khoa", b =>
                {
                    b.Property<string>("MaKhoa")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenKhoa")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaKhoa")
                        .HasName("PK__KHOA__653904057D92585F");

                    b.ToTable("KHOA", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Nganh", b =>
                {
                    b.Property<string>("MaNganh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("MaCt")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)")
                        .HasColumnName("MaCT");

                    b.Property<string>("MaKhoa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<string>("TenNganh")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("MaNganh")
                        .HasName("PK__NGANH__A2CEF50DA21238F5");

                    b.HasIndex("MaKhoa");

                    b.ToTable("NGANH", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Nhom", b =>
                {
                    b.Property<string>("MaNhom")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<string>("TenNhom")
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)")
                        .HasDefaultValueSql("(NULL)");

                    b.HasKey("MaNhom")
                        .HasName("PK__NHOM__234F91CDCE31D14F");

                    b.ToTable("NHOM", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Sinhvien", b =>
                {
                    b.Property<int>("MaSinhVien")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaSinhVien"));

                    b.Property<string>("Cccd")
                        .HasMaxLength(15)
                        .IsUnicode(false)
                        .HasColumnType("varchar(15)")
                        .HasColumnName("CCCD");

                    b.Property<string>("ChiNhanhNganHang")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("DiaChi")
                        .HasMaxLength(150)
                        .HasColumnType("nvarchar(150)");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("GioiTinh")
                        .HasColumnType("bit");

                    b.Property<string>("HoTen")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Lop")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("MaAccount")
                        .HasColumnType("int");

                    b.Property<string>("MaNganh")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<int?>("MaNhom")
                        .HasColumnType("int");

                    b.Property<string>("MaSoSinhVien")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)");

                    b.Property<DateOnly?>("NgaySinh")
                        .HasColumnType("date");

                    b.Property<string>("NienKhoa")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Sdt")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("SDT");

                    b.Property<string>("TknganHang")
                        .HasMaxLength(20)
                        .IsUnicode(false)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("TKNganHang");

                    b.HasKey("MaSinhVien");

                    b.HasIndex("MaAccount");

                    b.ToTable("SINHVIEN", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.ThongBaoChamLai", b =>
                {
                    b.Property<DateTime?>("DateModified")
                        .HasColumnType("datetime");

                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("IdDangKy")
                        .HasColumnType("int");

                    b.Property<bool?>("IsCheck")
                        .HasColumnType("bit");

                    b.Property<int?>("MaHoiDong")
                        .HasColumnType("int");

                    b.Property<string>("Thongbao")
                        .HasColumnType("ntext");

                    b.ToTable("ThongBaoChamLai", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Thongbao", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly?>("NgayGui")
                        .HasColumnType("date");

                    b.Property<int?>("NguoiNhan")
                        .HasColumnType("int");

                    b.Property<string>("NoiDungTb")
                        .HasColumnType("ntext");

                    b.Property<string>("TenThongBao")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.ToTable("THONGBAO", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Trangthai", b =>
                {
                    b.Property<int>("MaTrangThai")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTrangThai"));

                    b.Property<string>("TenTrangThai")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("MaTrangThai")
                        .HasName("PK__TRANGTHA__AADE4138B751F8C7");

                    b.ToTable("TRANGTHAI", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Typeaccount", b =>
                {
                    b.Property<int>("MaTypeAccount")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("MaTypeAccount"));

                    b.Property<string>("TenTypeAccount")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("MaTypeAccount")
                        .HasName("PK__TYPEACCO__4CA6144FEF9249B0");

                    b.ToTable("TYPEACCOUNT", (string)null);
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Account", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Typeaccount", "MaTypeAccountNavigation")
                        .WithMany("Accounts")
                        .HasForeignKey("MaTypeAccount")
                        .HasConstraintName("FK__ACCOUNT__MaTypeA__60A75C0F");

                    b.Navigation("MaTypeAccountNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Bienbannghiemthu", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Detai", "MaDeTaiNavigation")
                        .WithMany("Bienbannghiemthus")
                        .HasForeignKey("MaDeTai")
                        .HasConstraintName("FK__BIENBANNG__MaDeT__4BAC3F29");

                    b.HasOne("QuanLyMonHocDoAn.Models.Hoidongnghiemthu", "MaHoiDongNavigation")
                        .WithMany("Bienbannghiemthus")
                        .HasForeignKey("MaHoiDong")
                        .HasConstraintName("FK__BIENBANNG__MaHoi__4CA06362");

                    b.Navigation("MaDeTaiNavigation");

                    b.Navigation("MaHoiDongNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Detai", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Giangvien", "MaGiangVienNavigation")
                        .WithMany("Detais")
                        .HasForeignKey("MaGiangVien")
                        .HasConstraintName("FK__DETAI__MaGiangVi__5EBF139D");

                    b.HasOne("QuanLyMonHocDoAn.Models.Hoidongnghiemthu", "MaHoiDongNavigation")
                        .WithMany("Detais")
                        .HasForeignKey("MaHoiDong")
                        .HasConstraintName("FK__DETAI__MaHoiDong__4E88ABD4");

                    b.HasOne("QuanLyMonHocDoAn.Models.Nganh", "MaNganhNavigation")
                        .WithMany("Detais")
                        .HasForeignKey("MaNganh")
                        .HasConstraintName("FK__DETAI__MaNganh__4F7CD00D");

                    b.HasOne("QuanLyMonHocDoAn.Models.Trangthai", "MaTrangThaiNavigation")
                        .WithMany("Detais")
                        .HasForeignKey("MaTrangThai")
                        .HasConstraintName("FK__DETAI__MaTrangTh__5070F446");

                    b.Navigation("MaGiangVienNavigation");

                    b.Navigation("MaHoiDongNavigation");

                    b.Navigation("MaNganhNavigation");

                    b.Navigation("MaTrangThaiNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Donxingiahan", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Chitietdonxingiahan", "MaCtdxghNavigation")
                        .WithMany("Donxingiahans")
                        .HasForeignKey("MaCtdxgh")
                        .HasConstraintName("FK__DONXINGIA__MaCTD__6754599E");

                    b.HasOne("QuanLyMonHocDoAn.Models.Detai", "MaDeTaiNavigation")
                        .WithMany("Donxingiahans")
                        .HasForeignKey("MaDeTai")
                        .HasConstraintName("FK__DONXINGIA__MaDeT__52593CB8");

                    b.HasOne("QuanLyMonHocDoAn.Models.Giangvien", "MaGiangVienNavigation")
                        .WithMany("Donxingiahans")
                        .HasForeignKey("MaGiangVien")
                        .HasConstraintName("FK__DONXINGIA__MaGia__6477ECF3");

                    b.Navigation("MaCtdxghNavigation");

                    b.Navigation("MaDeTaiNavigation");

                    b.Navigation("MaGiangVienNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Hoidongnghiemthu", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Khoa", "MaKhoaNavigation")
                        .WithMany("Hoidongnghiemthus")
                        .HasForeignKey("MaKhoa")
                        .HasConstraintName("FK__HOIDONGNG__MaKho__5629CD9C");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Nganh", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Khoa", "MaKhoaNavigation")
                        .WithMany("Nganhs")
                        .HasForeignKey("MaKhoa")
                        .IsRequired()
                        .HasConstraintName("FK__NGANH__MaKhoa__59063A47");

                    b.Navigation("MaKhoaNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Sinhvien", b =>
                {
                    b.HasOne("QuanLyMonHocDoAn.Models.Account", "MaAccountNavigation")
                        .WithMany("Sinhviens")
                        .HasForeignKey("MaAccount")
                        .HasConstraintName("FK__SINHVIEN__MaAcco__571DF1D5");

                    b.Navigation("MaAccountNavigation");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Account", b =>
                {
                    b.Navigation("Sinhviens");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Chitietdonxingiahan", b =>
                {
                    b.Navigation("Donxingiahans");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Detai", b =>
                {
                    b.Navigation("Bienbannghiemthus");

                    b.Navigation("Donxingiahans");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Giangvien", b =>
                {
                    b.Navigation("Detais");

                    b.Navigation("Donxingiahans");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Hoidongnghiemthu", b =>
                {
                    b.Navigation("Bienbannghiemthus");

                    b.Navigation("Detais");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Khoa", b =>
                {
                    b.Navigation("Hoidongnghiemthus");

                    b.Navigation("Nganhs");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Nganh", b =>
                {
                    b.Navigation("Detais");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Trangthai", b =>
                {
                    b.Navigation("Detais");
                });

            modelBuilder.Entity("QuanLyMonHocDoAn.Models.Typeaccount", b =>
                {
                    b.Navigation("Accounts");
                });
#pragma warning restore 612, 618
        }
    }
}
